### ISSUE TITLE
Submit new Server

### ISSUE THREAD

**Issue by kilrau** [raiden-network/raiden-transport#7]
# URL
raidentransport.exchangeunion.com
# Hardware / Hosting
Google VPS 8vCPU/16GB/50GB
# Location
us-east1-d
# Monitoring
yes
# Intended uptime
24/7, but no alerting set up yet
# Who you are 
friends of a friend

**Comment by kilrau** [comment]
Up and running , thx @andrevmatos

**Comment by ulope** [comment]
@kilrau Could you please add the CNAME entry (`*.<domain>` -> `<domain>`) as mentioned in the installation instructions? Otherwise we can't (easily) access the monitoring service.

**Comment by kilrau** [comment]
Done: `*.raidentransport.exchangeunion.com` -> `raidentransport.exchangeunion.com`

**Comment by kilrau** [comment]
Also I did size down the machine a bit (4 vCPU, 6GB RAM) since this was Google's recommendation. I'll scale up once needed.
